// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/tanawit-dev/image-store/common/db"
	"github.com/tanawit-dev/image-store/common/minio"
	"github.com/tanawit-dev/image-store/config"
	"github.com/tanawit-dev/image-store/repositories"
	"github.com/tanawit-dev/image-store/routers"
	"github.com/tanawit-dev/image-store/server"
	"github.com/tanawit-dev/image-store/services"
)

// Injectors from wire.go:

func InitializeApplication() (*gin.Engine, error) {
	configuration := config.ProvideConfig()
	gormDB, err := db.ProvideDatabase(configuration)
	if err != nil {
		return nil, err
	}
	imageRepository := repositories.ProvideImageRepository(gormDB)
	imageStorage, err := minio.ProvideImageStorage(configuration)
	if err != nil {
		return nil, err
	}
	imageService := services.ProvideImageService(imageRepository, imageStorage, gormDB)
	imageController := routers.ProvideImageController(imageService)
	engine, err := server.ProvideServer(imageController)
	if err != nil {
		return nil, err
	}
	return engine, nil
}
